#!/bin/bash 
echo "Voulez-vous faire les mises à jour de votre machine (yes/no)"
read result
 if [ "$result" = "yes" ]; then
  sudo apt update
  sudo apt upgrade
  clear
  echo "mises a jour terminées"
  sleep 1.5
  clear
 elif [ "$result" = "no" ]; then
  echo "d'accord, bonne journée"
  sleep 1.5
  clear
 else
  echo "choix invalide"
 fi
